// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sati.Data;

#nullable disable

namespace Sati.Migrations
{
    [DbContext(typeof(SatiContext))]
    [Migration("20260815223729_AddAtRequestItemScreenshot")]
    partial class AddAtRequestItemScreenshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sati.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReviewItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewItemId")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Sati.Models.ATRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttestationStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseManagerAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseManagerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseManagerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEvergreenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<decimal>("SalesTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SalesTaxOverridden")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SignedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedByRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SignedByUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SnapshotPng")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorBillingContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorBillingLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorProgramContact")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ATRequests");
                });

            modelBuilder.Entity("Sati.Models.ATRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ATRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("ScreenshotPng")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ATRequestId");

                    b.ToTable("ATRequestItems");
                });

            modelBuilder.Entity("Sati.Models.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingModifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingProcedureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BillingUnitRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdiContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdiContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdiPayerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdiPayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdiSubmitterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Npi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Internal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sandbox Mode"
                        });
                });

            modelBuilder.Entity("Sati.Models.Assessments.ComprehensiveAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("PersonId", "Version")
                        .IsUnique();

                    b.ToTable("ComprehensiveAssessments");
                });

            modelBuilder.Entity("Sati.Models.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("AgencyId", "OccurredAtUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("Sati.Models.Billing.BillingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("BillingPeriods");
                });

            modelBuilder.Entity("Sati.Models.Billing.ClaimLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingPeriodId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClaimSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientMaineCareId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplianceExceptionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfService")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplianceException")
                        .HasColumnType("bit");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceOfService")
                        .HasColumnType("int");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedureModifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderingProviderNpi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Units")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillingPeriodId");

                    b.HasIndex("NoteId")
                        .IsUnique();

                    b.ToTable("ClaimLines");
                });

            modelBuilder.Entity("Sati.Models.Billing.EdiGeneration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<int>("BillingPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BillingPeriodId");

                    b.HasIndex("AgencyId", "ActorUserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("EdiGenerations");
                });

            modelBuilder.Entity("Sati.Models.ExemptDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExemptDates");
                });

            modelBuilder.Entity("Sati.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OpenedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Sati.Models.Incentive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DaysScheduled")
                        .HasColumnType("int");

                    b.Property<string>("ExcludedDatesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("PerUnitIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("Incentives");
                });

            modelBuilder.Entity("Sati.Models.IncidentGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("ExceptionFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstRelease")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastActorRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastRelease")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("int");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "LastSeenUtc");

                    b.HasIndex("AgencyId", "Scope", "Source", "Operation", "ExceptionFingerprint")
                        .IsUnique();

                    b.ToTable("IncidentGroups");
                });

            modelBuilder.Entity("Sati.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("CaseManagerJustification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ComplianceOverride")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FormType")
                        .HasColumnType("int");

                    b.Property<int?>("Minutes")
                        .HasColumnType("int");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoteType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OverrideApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OverrideApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReturnedById")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int?>("StartTime")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VisitDocumentationJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("PersonId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Sati.Models.PersonContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("HasActiveRelease")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmergencyContact")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Organization")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "IsActive");

                    b.ToTable("PersonContacts");
                });

            modelBuilder.Entity("Sati.Models.PersonVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ChangesGzip")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SnapshotGzip")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "ChangedAtUtc");

                    b.HasIndex("PersonId", "Version")
                        .IsUnique();

                    b.ToTable("PersonVersions");
                });

            modelBuilder.Entity("Sati.Models.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("BillingContact")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BillingLocationEis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaineCareProviderId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Npi")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("OfferedServices")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimaryContact")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProgramContact")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("ProvidesPassthroughService")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Street")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Zip")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "MaineCareProviderId")
                        .IsUnique()
                        .HasFilter("[MaineCareProviderId] IS NOT NULL");

                    b.HasIndex("AgencyId", "Name");

                    b.HasIndex("AgencyId", "Npi")
                        .IsUnique()
                        .HasFilter("[Npi] IS NOT NULL");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Sati.Models.Scratchpad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Scratchpad");
                });

            modelBuilder.Entity("Sati.Models.ScratchpadComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScratchpadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScratchpadId", "CreatedAtUtc");

                    b.ToTable("ScratchpadComments");
                });

            modelBuilder.Entity("Sati.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbandonedAfterDays")
                        .HasColumnType("int");

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompAssessmentDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("CompAssessmentDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("CompAssessmentOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<string>("ContactTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultPassthroughProviderId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentationTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExcludeChristmas")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeDayAfterThanksgiving")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeFriday")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeIndependenceDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeIndigenousPeoplesDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeJuneteenth")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeLaborDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeMLKDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeMemorialDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeMonday")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeNewYearsDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludePresidentsDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeThanksgiving")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeThursday")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeTuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeVeteransDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeWednesday")
                        .HasColumnType("bit");

                    b.Property<string>("HealthcareSystemsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[\"Other\"]");

                    b.Property<decimal>("PassthroughRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.15m);

                    b.Property<int>("PcpDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("PcpDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("PcpOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<decimal>("PerUnitIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrivacyPracticesDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyPracticesDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyPracticesOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ProductivityThreshold")
                        .HasColumnType("int");

                    b.Property<int>("Q4RDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("ReclassificationDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReclassificationDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("ReclassificationOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseAgencyDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseAgencyDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseAgencyOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseDhhsDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseDhhsDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseDhhsOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseMedicalDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseMedicalDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseMedicalOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ReviewDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReviewOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("SafetyPlanDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("SafetyPlanDaysBeforeAnniversary")
                        .HasColumnType("int");

                    b.Property<int>("SafetyPlanOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<decimal>("SalesTaxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.055m);

                    b.Property<string>("VisitTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId")
                        .IsUnique();

                    b.HasIndex("DefaultPassthroughProviderId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Sati.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sati.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("BillingCity")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BillingState")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("BillingStreet")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("BillingZip")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayProgramCount")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosisCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvergreenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasCommunitySupport1To1")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCommunitySupportDayProgram")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCommunitySupportSelfDirected")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEmploymentSpecialist")
                        .HasColumnType("bit");

                    b.Property<bool>("HasGuardian")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHomeSupport")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSelfDirectedHomeSupport")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSharedLiving")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWorkSupports")
                        .HasColumnType("bit");

                    b.Property<string>("HealthcareSystemName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEmployed")
                        .HasColumnType("bit");

                    b.Property<string>("Journal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaineCareId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OpenWithVR")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PlaceOfService")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryCareProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Waiver")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("UserId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Sati.ReviewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CycleAnchor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LoggedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "CycleAnchor", "Quarter", "Category", "SlotIndex")
                        .IsUnique();

                    b.ToTable("ReviewItems");
                });

            modelBuilder.Entity("Sati.Appointment", b =>
                {
                    b.HasOne("Sati.ReviewItem", "ReviewItem")
                        .WithOne("Appointment")
                        .HasForeignKey("Sati.Appointment", "ReviewItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewItem");
                });

            modelBuilder.Entity("Sati.Models.ATRequest", b =>
                {
                    b.HasOne("Sati.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.ATRequestItem", b =>
                {
                    b.HasOne("Sati.Models.ATRequest", "ATRequest")
                        .WithMany("Items")
                        .HasForeignKey("ATRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ATRequest");
                });

            modelBuilder.Entity("Sati.Models.Assessments.ComprehensiveAssessment", b =>
                {
                    b.HasOne("Sati.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sati.Models.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sati.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.Billing.BillingPeriod", b =>
                {
                    b.HasOne("Sati.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sati.Models.Billing.ClaimLine", b =>
                {
                    b.HasOne("Sati.Models.Billing.BillingPeriod", "BillingPeriod")
                        .WithMany("Lines")
                        .HasForeignKey("BillingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sati.Models.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingPeriod");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Sati.Models.Billing.EdiGeneration", b =>
                {
                    b.HasOne("Sati.Models.Billing.BillingPeriod", "BillingPeriod")
                        .WithMany()
                        .HasForeignKey("BillingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingPeriod");
                });

            modelBuilder.Entity("Sati.Models.ExemptDate", b =>
                {
                    b.HasOne("Sati.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sati.Models.Form", b =>
                {
                    b.HasOne("Sati.Person", "Person")
                        .WithMany("Forms")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.Incentive", b =>
                {
                    b.HasOne("Sati.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sati.Models.IncidentGroup", b =>
                {
                    b.HasOne("Sati.Models.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sati.Models.Note", b =>
                {
                    b.HasOne("Sati.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sati.Person", "Person")
                        .WithMany("Notes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.PersonContact", b =>
                {
                    b.HasOne("Sati.Person", "Person")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.PersonVersion", b =>
                {
                    b.HasOne("Sati.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.Provider", b =>
                {
                    b.HasOne("Sati.Models.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sati.Models.ScratchpadComment", b =>
                {
                    b.HasOne("Sati.Models.Scratchpad", "Scratchpad")
                        .WithMany("Comments")
                        .HasForeignKey("ScratchpadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scratchpad");
                });

            modelBuilder.Entity("Sati.Models.Settings", b =>
                {
                    b.HasOne("Sati.Models.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sati.Models.Provider", null)
                        .WithMany()
                        .HasForeignKey("DefaultPassthroughProviderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Sati.Models.User", b =>
                {
                    b.HasOne("Sati.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sati.Models.User", "Supervisor")
                        .WithMany("Supervisees")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agency");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Sati.Person", b =>
                {
                    b.HasOne("Sati.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sati.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sati.ReviewItem", b =>
                {
                    b.HasOne("Sati.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.ATRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sati.Models.Billing.BillingPeriod", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Sati.Models.Scratchpad", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Sati.Models.User", b =>
                {
                    b.Navigation("Supervisees");
                });

            modelBuilder.Entity("Sati.Person", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Forms");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Sati.ReviewItem", b =>
                {
                    b.Navigation("Appointment");
                });
#pragma warning restore 612, 618
        }
    }
}
